name: "Add comentario"
description: "Add comentario em uma action composite"
author: "Fernando Spelling"
inputs:
  GITHUB_TOKEN:
    description: "Token dq qpi do GitHub com permissão para adicionar comentários"
    required: true
  issue-id:
    description: "Número da issue ou pull request onde o comentário será adicionado"
    required: true
  comment:
    description: "Conteúdo do comentário a ser adicionado"
    required: true
outputs:
  comment_id:
    description: "ID do comentário adicionado"
    value: ${{ steps.comment-action.outputs.comment-id }}
runs:
  using: "composite"
  steps:
    - name: Adicionando comentário
      id: comment-action
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        ISSUE_ID: ${{ inputs.issue-id }}
        COMMENT: ${{ inputs.comment }}
      run: |
        GITHUB_TOKEN=$GITHUB_TOKEN
        ISSUE_ID=$ISSUE_ID
        COMMENT=$COMMENT

        # Inicialize o cliente do GitHub
        response=$(curl -s -X POST -H "Authorization: token ${GITHUB_TOKEN}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${ISSUE_ID}/comments \
            -d "{\"body\": \"${COMMENT}\"}")

        # Obtenha o ID do comentário criado
        comment_id=$(echo $response | jq -r .id)

        echo 

        # Define o output com o ID do comentário

        echo "comment-id=$(echo $comment_id)" >> $GITHUB_OUTPUT


        echo "Comentário adicionado com sucesso! ID do comentário: $comment_id"

